### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by jaynnnnn** [Gekkoou/dnmp#1]
![image](https://user-images.githubusercontent.com/33743760/130762663-03c09a13-09d3-4a16-b014-6746e7577ab2.png)
这个有问题啊 兄弟

**Comment by Gekkoou** [comment]
> ![image](https://user-images.githubusercontent.com/33743760/130762663-03c09a13-09d3-4a16-b014-6746e7577ab2.png)
> 这个有问题啊 兄弟

已解决, 感谢老哥
